export interface Bot {
  name: string;
  userAgent: string;
  company: string;
  type: "ai-crawler" | "ai-search" | "search-engine" | "social" | "other";
  description: string;
  docsUrl: string;
  defaultBlocked: boolean;
}

export const AI_BOTS: Bot[] = [
  {
    name: "GPTBot",
    userAgent: "GPTBot",
    company: "OpenAI",
    type: "ai-crawler",
    description: "Used by OpenAI to crawl web pages for training data and ChatGPT web browsing",
    docsUrl: "https://platform.openai.com/docs/bots/gptbot",
    defaultBlocked: false,
  },
  {
    name: "ChatGPT-User",
    userAgent: "ChatGPT-User",
    company: "OpenAI",
    type: "ai-search",
    description: "ChatGPT browsing feature when users ask it to search the web",
    docsUrl: "https://platform.openai.com/docs/bots/chatgpt-user",
    defaultBlocked: false,
  },
  {
    name: "OAI-SearchBot",
    userAgent: "OAI-SearchBot",
    company: "OpenAI",
    type: "ai-search",
    description: "OpenAI's dedicated search crawler for SearchGPT",
    docsUrl: "https://platform.openai.com/docs/bots",
    defaultBlocked: false,
  },
  {
    name: "ClaudeBot",
    userAgent: "ClaudeBot",
    company: "Anthropic",
    type: "ai-crawler",
    description: "Used by Anthropic to crawl web content for Claude's training",
    docsUrl: "https://docs.anthropic.com/en/docs/about-claude/crawlers",
    defaultBlocked: false,
  },
  {
    name: "anthropic-ai",
    userAgent: "anthropic-ai",
    company: "Anthropic",
    type: "ai-crawler",
    description: "Anthropic's general web crawler",
    docsUrl: "https://docs.anthropic.com/en/docs/about-claude/crawlers",
    defaultBlocked: false,
  },
  {
    name: "Google-Extended",
    userAgent: "Google-Extended",
    company: "Google",
    type: "ai-crawler",
    description: "Controls access to content used for Gemini training (does NOT affect Google Search)",
    docsUrl: "https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers",
    defaultBlocked: false,
  },
  {
    name: "Gemini",
    userAgent: "Google-Safety",
    company: "Google",
    type: "ai-search",
    description: "Google's AI assistant web access",
    docsUrl: "https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers",
    defaultBlocked: false,
  },
  {
    name: "PerplexityBot",
    userAgent: "PerplexityBot",
    company: "Perplexity",
    type: "ai-search",
    description: "Perplexity AI's web crawler for real-time search answers",
    docsUrl: "https://docs.perplexity.ai/guides/perplexitybot",
    defaultBlocked: false,
  },
  {
    name: "CCBot",
    userAgent: "CCBot",
    company: "Common Crawl",
    type: "ai-crawler",
    description: "Common Crawl's bot — dataset widely used for AI training by many companies",
    docsUrl: "https://commoncrawl.org/ccbot",
    defaultBlocked: false,
  },
  {
    name: "Bytespider",
    userAgent: "Bytespider",
    company: "ByteDance",
    type: "ai-crawler",
    description: "ByteDance's crawler used for TikTok and AI model training",
    docsUrl: "https://darkvisitors.com/agents/bytespider",
    defaultBlocked: true,
  },
  {
    name: "Diffbot",
    userAgent: "Diffbot",
    company: "Diffbot",
    type: "ai-crawler",
    description: "Web scraping and knowledge graph construction",
    docsUrl: "https://docs.diffbot.com/reference/crawl",
    defaultBlocked: false,
  },
  {
    name: "cohere-ai",
    userAgent: "cohere-ai",
    company: "Cohere",
    type: "ai-crawler",
    description: "Cohere's web crawler for AI model training",
    docsUrl: "https://docs.cohere.com/docs/web-crawler",
    defaultBlocked: false,
  },
  {
    name: "Amazonbot",
    userAgent: "Amazonbot",
    company: "Amazon",
    type: "ai-crawler",
    description: "Amazon's crawler for Alexa AI and product search",
    docsUrl: "https://developer.amazon.com/amazonbot",
    defaultBlocked: false,
  },
  {
    name: "Meta-ExternalAgent",
    userAgent: "Meta-ExternalAgent",
    company: "Meta",
    type: "ai-crawler",
    description: "Meta's crawler for AI training data collection",
    docsUrl: "https://developers.facebook.com/docs/sharing/bot",
    defaultBlocked: false,
  },
  {
    name: "Meta-ExternalFetcher",
    userAgent: "Meta-ExternalFetcher",
    company: "Meta",
    type: "ai-crawler",
    description: "Meta's fetcher for AI product features",
    docsUrl: "https://developers.facebook.com/docs/sharing/bot",
    defaultBlocked: false,
  },
  {
    name: "AppleBot-Extended",
    userAgent: "Applebot-Extended",
    company: "Apple",
    type: "ai-crawler",
    description: "Apple's crawler for Apple Intelligence and Siri training",
    docsUrl: "https://support.apple.com/en-us/111855",
    defaultBlocked: false,
  },
  {
    name: "YouBot",
    userAgent: "YouBot",
    company: "You.com",
    type: "ai-search",
    description: "You.com AI search engine crawler",
    docsUrl: "https://about.you.com/youbot/",
    defaultBlocked: false,
  },
  {
    name: "Timpibot",
    userAgent: "Timpibot",
    company: "Timpi",
    type: "ai-crawler",
    description: "Decentralized search engine and AI data crawler",
    docsUrl: "https://timpi.io",
    defaultBlocked: true,
  },
  {
    name: "Scrapy",
    userAgent: "Scrapy",
    company: "Open Source",
    type: "other",
    description: "Popular open-source web scraping framework",
    docsUrl: "https://scrapy.org",
    defaultBlocked: true,
  },
  {
    name: "img2dataset",
    userAgent: "img2dataset",
    company: "Open Source",
    type: "ai-crawler",
    description: "Image dataset collection tool commonly used for AI training",
    docsUrl: "https://github.com/rom1504/img2dataset",
    defaultBlocked: true,
  },
];

export const SEARCH_ENGINE_BOTS: Bot[] = [
  {
    name: "Googlebot",
    userAgent: "Googlebot",
    company: "Google",
    type: "search-engine",
    description: "Google Search crawler — blocking this removes you from Google Search",
    docsUrl: "https://developers.google.com/search/docs/crawling-indexing/googlebot",
    defaultBlocked: false,
  },
  {
    name: "Bingbot",
    userAgent: "Bingbot",
    company: "Microsoft",
    type: "search-engine",
    description: "Bing Search crawler",
    docsUrl: "https://www.bing.com/webmasters/help/which-crawlers-does-bing-use-8c184ec0",
    defaultBlocked: false,
  },
  {
    name: "YandexBot",
    userAgent: "YandexBot",
    company: "Yandex",
    type: "search-engine",
    description: "Yandex search engine crawler",
    docsUrl: "https://yandex.com/support/webmaster/robot-workings/check-yandex-robots.html",
    defaultBlocked: false,
  },
  {
    name: "Baiduspider",
    userAgent: "Baiduspider",
    company: "Baidu",
    type: "search-engine",
    description: "Baidu search engine crawler (China)",
    docsUrl: "https://www.baidu.com/search/robots_english.html",
    defaultBlocked: false,
  },
  {
    name: "DuckDuckBot",
    userAgent: "DuckDuckBot",
    company: "DuckDuckGo",
    type: "search-engine",
    description: "DuckDuckGo search engine crawler",
    docsUrl: "https://duckduckgo.com/duckduckbot",
    defaultBlocked: false,
  },
];

export const ALL_BOTS = [...AI_BOTS, ...SEARCH_ENGINE_BOTS];
