import { ALL_BOTS, type Bot } from "./bots";

export interface RobotsRule {
  userAgent: string;
  rules: { type: "allow" | "disallow"; path: string }[];
}

export interface ParsedRobots {
  rules: RobotsRule[];
  sitemaps: string[];
  raw: string;
}

export function parseRobotsTxt(content: string): ParsedRobots {
  const lines = content.split("\n").map((l) => l.trim());
  const rules: RobotsRule[] = [];
  const sitemaps: string[] = [];
  let currentRule: RobotsRule | null = null;

  for (const line of lines) {
    if (!line || line.startsWith("#")) continue;

    const lower = line.toLowerCase();

    if (lower.startsWith("user-agent:")) {
      const ua = line.slice("user-agent:".length).trim();
      if (currentRule && currentRule.rules.length === 0) {
        currentRule.userAgent = ua;
      } else {
        currentRule = { userAgent: ua, rules: [] };
        rules.push(currentRule);
      }
    } else if (lower.startsWith("disallow:") && currentRule) {
      const path = line.slice("disallow:".length).trim();
      if (path) {
        currentRule.rules.push({ type: "disallow", path });
      }
    } else if (lower.startsWith("allow:") && currentRule) {
      const path = line.slice("allow:".length).trim();
      if (path) {
        currentRule.rules.push({ type: "allow", path });
      }
    } else if (lower.startsWith("sitemap:")) {
      const url = line.slice("sitemap:".length).trim();
      if (url) sitemaps.push(url);
    }
  }

  return { rules, sitemaps, raw: content };
}

export interface BotStatus {
  bot: Bot;
  blocked: boolean;
  rules: string[];
}

export function analyzeBots(parsed: ParsedRobots): BotStatus[] {
  return ALL_BOTS.map((bot) => {
    const matchingRules: string[] = [];
    let blocked = false;

    for (const rule of parsed.rules) {
      const ua = rule.userAgent.toLowerCase();
      if (ua === "*" || ua === bot.userAgent.toLowerCase()) {
        for (const r of rule.rules) {
          if (r.type === "disallow" && r.path === "/") {
            blocked = true;
            matchingRules.push(`Disallow: /`);
          } else if (r.type === "disallow") {
            matchingRules.push(`Disallow: ${r.path}`);
          } else if (r.type === "allow" && r.path === "/") {
            blocked = false;
            matchingRules.push(`Allow: /`);
          }
        }
      }
    }

    return { bot, blocked, rules: matchingRules };
  });
}

export interface BotToggleState {
  [userAgent: string]: boolean;
}

export function generateRobotsTxt(
  blockedBots: BotToggleState,
  sitemapUrls: string[],
  customRules: string
): string {
  const lines: string[] = [];

  lines.push("# robots.txt generated by robotstxt.ai");
  lines.push(`# Generated: ${new Date().toISOString().split("T")[0]}`);
  lines.push("");

  // Wildcard rule — allow all by default
  lines.push("# Allow all crawlers by default");
  lines.push("User-agent: *");
  lines.push("Allow: /");
  lines.push("");

  // Group blocked bots
  const blocked = Object.entries(blockedBots).filter(([, isBlocked]) => isBlocked);

  if (blocked.length > 0) {
    lines.push("# AI Crawlers - Blocked");
    for (const [userAgent] of blocked) {
      lines.push(`User-agent: ${userAgent}`);
      lines.push("Disallow: /");
      lines.push("");
    }
  }

  // Custom rules
  if (customRules.trim()) {
    lines.push("# Custom Rules");
    lines.push(customRules.trim());
    lines.push("");
  }

  // Sitemaps
  if (sitemapUrls.length > 0) {
    lines.push("# Sitemaps");
    for (const url of sitemapUrls) {
      if (url.trim()) {
        lines.push(`Sitemap: ${url.trim()}`);
      }
    }
    lines.push("");
  }

  return lines.join("\n");
}
